[features]
minimal_title_screen = true
no_crop_trampling = true
stackable_food = true
log_version = true
single_pixel_crosshair = true
raw_squid_and_calamari = true
fortress_bricks = true
fixed_time = false
debug_fov = false
hunger_and_thirst = false # do not enable, this is unfinished
debug_recipes = false # do not enable, gives you overpowered recipe for debugging
